name: Terragrunt Config Export

on:
  push:
    branches:
      - master
    paths:
      - 'terragrunt-config-export/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'terragrunt-config-export/**'

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: terragrunt-config-export
          file: terragrunt-config-export/Dockerfile
          push: true
          tags: sykescottages/bitbucket-pipes:terragrunt-config-export